#!/bin/sh
# Pre-commit hook

# Regenerate llms-full.txt if any docs files are staged.
DOC_CHANGES=$(git diff --cached --name-only | grep -E '^docs/.*\.md$')
if [ -n "$DOC_CHANGES" ]; then
    ./scripts/gen-llms-full.sh
    git add docs/llms-full.txt
fi
